### ISSUE TITLE
byte/uint8 stream

### ISSUE THREAD

**Issue by arkanoid87** [sealmove/binarylang#1]
while dealing with stream of data from C library, I had to convert:
```nim
data*: ptr uint8
size*: uint64
```
Into something I can parse with binarylang. So I did:
```nim
var arraydata = cast[ptr UncheckedArray[uint8]](data)
var sstring: string = newString(size)
for i in 0..size-1:
  sstring[i] = char(arraydata[i])
var inputss = newStringBitStream(sstring)
var parsedData = myParser.get(inputss)
```
Quite a long trip.

as streams module lacks byte stream support. What about adding newBitStream(data: openArray[byte]) or something similar to bitstreams?

**Comment by sealmove** [comment]
Thanks for the issue. The reason there isn't such a proc is because stdlib itself doesn't provide it and I want to keep the mapping between a `Bitstream` and a regular stdlib's `Stream` obvious. I am hesitant to hide such code in the [bitstreams](https://github.com/sealmove/bitstreams) library. I recognize it's a very common case and thus annoying to not have such a proc by default, but you can always write a wrapper around `newStringBitStream`, right?

**Comment by arkanoid87** [comment]
Yeah, it is probably safer to stick ti std. I have wrapped up a solution inside my project. Thanks!

**Comment by sealmove** [comment]
@arkanoid87 By the way I am interested to hear what you are working on, as few people are using binarylang. Can you share any contact info (or maybe you are on Nim IRC/Discord)?

**Comment by arkanoid87** [comment]
Sure! We've already been talking on IRC, you can find me as "giaco"
