### ISSUE TITLE
Put example

### ISSUE THREAD

**Issue by bluemax75** [sealmove/binarylang#18]
Could you add an example of how to build a message with the put procedure? All the tests use the previous get and I'm trying to build a message without success.
The first problem I get into is the deprecation of typeGetter. How may I use the type directly?
If I use typeGetter nevertheless I get a segmentation fault when I try to set the values:

```nim
import binarylang

struct(hello):
  8: *first

proc main() =
  var data: typeGetter(hello)
  data.first = 3
  var stout = newStringBitStream()
  hello.put(stout, data)

main()
```

**Comment by sealmove** [comment]
First of all, instead of `typeGetter(hello)`, simply use `Hello` (name of parser capitalized). Also, the convenient procs `toHello` and `fromHello` are generated. Lastly, you are getting segmentation fault because your `data` object is not initialized, so when you do `data.first = 3` your are trying to access the field `first`, but `data` is `nil`.

**Comment by bluemax75** [comment]
Thanks for the quick response! I knew I was doing something wrong and even saw the warning over the typeGetter but could not find an example usage
Using the parser name capitalized work perfectly:
```nim
var data = Hello()
data.first = 3
```

**Comment by sealmove** [comment]
with `typeGetter` it would be:
```nim
 var data: typeGetter(hello)()
```
to contruct an object

**Comment by bluemax75** [comment]
I think the reason I was using it incorrectly is that I started using binaryparse before changing to binarylang.
Thank you for this excellent library
